services:
  iobroker-dashboard:
    image: ghcr.io/andymann/iobroker-dashboard:latest
    restart: unless-stopped
    ports:
      - "8090:8080"
    environment:
      IOBROKER_HOST:   "http://192.168.178.53:8087"
      IOBROKER_STATES: "zigbee.0.44e2f8fffe61d5d9.state,zigbee.0.44e2f8fffe61d5d9.colortemp,zigbee.0.8c65a3fffef115e2.state"
      LISTEN_PORT:     "8080"
      FETCH_TIMEOUT:   "5"